### ISSUE TITLE
Make Ashrae constructions for windows

### ISSUE THREAD

**Issue by santoshphilip** [pyenergyplus/py90dot1#32]
**Problem**: `py90dot1.setallconstructions.setconstruction(idf, climatezone)` is supposed to make all the constructions in the model into ASHRAE constructions for the climate zone. It does not set the constructions for the windows
**Soultion**: make py90dot1.setallconstructions.setconstruction(idf, climatezone) put in the window construction. Do this only for `FENESTRATIONSURFACE:DETAILED`. The other window objects can be done later

Comments:

- `py90dot1.setallconstructions.setconstruction` works only for one climate zone right now
- `py90dot1.setallconstructions.setconstruction` works only for surface objects `BUILDINGSURFACE:DETAILED`
- Leave it that way for now. 
- We can open a new issue to go beyond this.

**Comment by nathan** [comment]
@pyenergyplus you probably meant @ncbrown

**Comment by santoshphilip** [comment]
yup ! I'll fix that.
