### ISSUE TITLE
run py90dot1 from the command line

### ISSUE THREAD

**Issue by santoshphilip** [pyenergyplus/py90dot1#34]
**Problem**: py90dot1 cannot be run from the command line
**Solution**: Have something like 

`python py90dot1.py proposed_idffile climatezone weatherfile`

that will output the baseline IDF

**Comment by pyenergyplus** [comment]
reopening this issue for discussion. Most of my comments are in #36

**Comment by pyenergyplus** [comment]
dammit ... I am commenting as the admin @pyenergyplus.
I should be commenting as @santoshphilip 

@pyenergyplus should not be saying anything at all.
Will try to fix that :-(

**Comment by santoshphilip** [comment]
Ok .... switched to writing comments as @santoshphilip
Sorry for the mess of notification emails
