### ISSUE TITLE
package setup

### ISSUE THREAD

**Issue by ncbrown** [pyenergyplus/py90dot1#35]
@santoshphilip 

I have cloned the repo and installed requirements using pip.

I run py.test, which fails for two tests with the same error:

```
def test_surfacefilter():
       """py.test for surfacefilter"""
        idftxt = IdfData.idftxt
        wallnames = set(['South_Wall', 'North_Wall', 'Roof_Wall', 'East_Wall', 'West_Wall'])
        floornames = set(['Floor_Outdoor'])
        roofnames = set(['Roof_Roof'])
\>       fhandle = io.StringIO(idftxt)
E       TypeError: initial_value must be unicode or None, not str
```
I suspect this may be a python 3 issue? I'm running python 2.7.10. Do you have advice for how to run this on my machine?

**Comment by santoshphilip** [comment]
py90dot1 is going to be pure python3 (no python2 - it is new code .. no need for backward compatibility)

to make a virtualenv for python3 try the following steps:

    # to work in python3
    pyvenv ~/venvs/py3_90dot1 # make virtualenv
    source ~/venvs/py3_90dot1/bin/activate # activate it

You me need to take other steps like install python3. Let me know what it takes. I'll add it to the developer documentation.

**Comment by santoshphilip** [comment]
Let me know when you get running on this. We can close this issue

**Comment by ncbrown** [comment]
I think we can close the issue - do i do that?

**Comment by santoshphilip** [comment]
I'll close
